name: Build and push

on:
  workflow_dispatch:
    inputs:
      skip-build:
        type: boolean
        required: true
        default: true
        description: Skip docker build
      environment:
        type: choice
        required: false
        description: "Environment where to deploy"
        options:
          - dev-cd
          - uat-cd


env:
  TARGET_PLATFORMS: linux/arm64

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    outputs:
      docker-tags: ${{ steps.meta.outputs.tags }}
    permissions:
      id-token: write
      packages: write
      contents: write

    steps:
      - name: Checkout the source code
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 #v3.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 #v3.0.0

      - name: Log in to the Container registry
        id: docker_login
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d #v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} # must be a bot token ${{ secrets.BOT_WRITE_PACKAGE_TOKEN }}

      - name: Generate Docker Metadata
        id: meta
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81 #v5.5.1
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}}
            type=ref,event=branch
          labels: |
            maintainer=https://pagopa.it
            org.opencontainers.image.source=https://github.com/${{ github.repository }}

      - name: Build and push Docker image
        if: ${{ inputs.skip-build == 'false' }}
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 #v5.0.0
        with:
          file: src/main/docker/Dockerfile.native-micro
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: ${{ env.TARGET_PLATFORMS }}


  deploy:
    needs: [build_and_push]
    name: Deploy on ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Login to Azure
        uses: azure/login@92a5484dfaf04ca78a94597f4f19fea633851fa2
        with:
          client-id: ${{ secrets.AZURE_CD_IDENTITY_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_CD_IDENTITY_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Get image tag to deploy
        id: tagToDeploy
        run: echo "::set-output name=tag::$(echo ${{ build_and_push.outputs.docker-tags }} | awk '{print $1}')"

      - name: Deploy Container App
        uses: azure/container-apps-deploy-action@02d045129c058b13312276b50a552834cf74e2af #v2.0.0
        with:
          containerAppName: ${{ secrets.AZURE_CONTAINER_APP_NAME }}
          resourceGroup: ${{ secrets.AZURE_RESOURCE_GROUP_NAME }}
          imageToDeploy: ${{ steps.tagToDeploy.tag }}
